# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(750, 476)
        Form.setMinimumSize(QtCore.QSize(750, 476))
        Form.setMaximumSize(QtCore.QSize(750, 546))
        Form.setMouseTracking(True)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setMouseTracking(True)
        self.frame.setStyleSheet("#frame {\n"
"image: url(:/icon/image/flow/模型适配工具-欢迎页.png);\n"
"}\n"
"* {\n"
"border-style: none;\n"
"border-radius: 5px 5px;\n"
"background-color: #FEFEFE;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(32, -1, 32, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_3 = QtWidgets.QFrame(self.frame)
        self.title_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_3.sizePolicy().hasHeightForWidth())
        self.title_3.setSizePolicy(sizePolicy)
        self.title_3.setMinimumSize(QtCore.QSize(0, 20))
        self.title_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setBold(False)
        font.setWeight(50)
        self.title_3.setFont(font)
        self.title_3.setMouseTracking(True)
        self.title_3.setStyleSheet("background:rgba(0,0,0,0)")
        self.title_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_3.setObjectName("title_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.title_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2.addWidget(self.title_3)
        self.warning = QtWidgets.QFrame(self.frame)
        self.warning.setEnabled(True)
        self.warning.setMinimumSize(QtCore.QSize(0, 32))
        self.warning.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setBold(False)
        font.setWeight(50)
        self.warning.setFont(font)
        self.warning.setMouseTracking(True)
        self.warning.setStyleSheet("")
        self.warning.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.warning.setFrameShadow(QtWidgets.QFrame.Raised)
        self.warning.setObjectName("warning")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.warning)
        self.horizontalLayout_5.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.warning_1 = QtWidgets.QFrame(self.warning)
        self.warning_1.setEnabled(True)
        self.warning_1.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setBold(False)
        font.setWeight(50)
        self.warning_1.setFont(font)
        self.warning_1.setMouseTracking(True)
        self.warning_1.setStyleSheet("background-color: rgb(253, 217, 188);")
        self.warning_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.warning_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.warning_1.setObjectName("warning_1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.warning_1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.warning_button = QtWidgets.QPushButton(self.warning_1)
        self.warning_button.setEnabled(True)
        self.warning_button.setMinimumSize(QtCore.QSize(32, 32))
        self.warning_button.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.warning_button.setFont(font)
        self.warning_button.setMouseTracking(True)
        self.warning_button.setStyleSheet("")
        self.warning_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/image/alarm-orange.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.warning_button.setIcon(icon)
        self.warning_button.setObjectName("warning_button")
        self.horizontalLayout_6.addWidget(self.warning_button)
        self.warning_label_1 = QtWidgets.QLabel(self.warning_1)
        self.warning_label_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warning_label_1.sizePolicy().hasHeightForWidth())
        self.warning_label_1.setSizePolicy(sizePolicy)
        self.warning_label_1.setMinimumSize(QtCore.QSize(0, 0))
        self.warning_label_1.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.warning_label_1.setFont(font)
        self.warning_label_1.setMouseTracking(True)
        self.warning_label_1.setStyleSheet("color: #000000;\n"
"background:rgba(0,0,0,0);\n"
"")
        self.warning_label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.warning_label_1.setObjectName("warning_label_1")
        self.horizontalLayout_6.addWidget(self.warning_label_1)
        self.warning_label_2 = QtWidgets.QLabel(self.warning_1)
        self.warning_label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warning_label_2.sizePolicy().hasHeightForWidth())
        self.warning_label_2.setSizePolicy(sizePolicy)
        self.warning_label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.warning_label_2.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.warning_label_2.setFont(font)
        self.warning_label_2.setMouseTracking(True)
        self.warning_label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.warning_label_2.setStyleSheet("color: #0077FF;\n"
"background:rgba(0,0,0,0);\n"
"")
        self.warning_label_2.setText("<A style=\'color: #0077FF; text-decoration: none\'href=\'https://www.baidu.com\'>安装指引</A>")
        self.warning_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.warning_label_2.setOpenExternalLinks(False)
        self.warning_label_2.setObjectName("warning_label_2")
        self.horizontalLayout_6.addWidget(self.warning_label_2)
        self.warning_label_3 = QtWidgets.QLabel(self.warning_1)
        self.warning_label_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warning_label_3.sizePolicy().hasHeightForWidth())
        self.warning_label_3.setSizePolicy(sizePolicy)
        self.warning_label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.warning_label_3.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.warning_label_3.setFont(font)
        self.warning_label_3.setMouseTracking(True)
        self.warning_label_3.setStyleSheet("color: #000000;\n"
"background:rgba(0,0,0,0);\n"
"")
        self.warning_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.warning_label_3.setObjectName("warning_label_3")
        self.horizontalLayout_6.addWidget(self.warning_label_3)
        self.horizontalLayout_5.addWidget(self.warning_1)
        self.verticalLayout_2.addWidget(self.warning)
        self.title = QtWidgets.QFrame(self.frame)
        self.title.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setMinimumSize(QtCore.QSize(0, 0))
        self.title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setBold(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setMouseTracking(True)
        self.title.setStyleSheet("background:rgba(0,0,0,0)")
        self.title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title.setObjectName("title")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.title)
        self.verticalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.title_button = QtWidgets.QPushButton(self.title)
        self.title_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_button.sizePolicy().hasHeightForWidth())
        self.title_button.setSizePolicy(sizePolicy)
        self.title_button.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.title_button.setFont(font)
        self.title_button.setMouseTracking(True)
        self.title_button.setStyleSheet("")
        self.title_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/image/flow/编组.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.title_button.setIcon(icon1)
        self.title_button.setIconSize(QtCore.QSize(140, 60))
        self.title_button.setObjectName("title_button")
        self.verticalLayout_3.addWidget(self.title_button)
        self.title_label = QtWidgets.QLabel(self.title)
        self.title_label.setEnabled(False)
        self.title_label.setMinimumSize(QtCore.QSize(0, 0))
        self.title_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.title_label.setFont(font)
        self.title_label.setMouseTracking(True)
        self.title_label.setStyleSheet("color: #000000;\n"
"background:rgba(0,0,0,0);")
        self.title_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout_3.addWidget(self.title_label)
        self.verticalLayout_2.addWidget(self.title)
        self.status = QtWidgets.QFrame(self.frame)
        self.status.setEnabled(True)
        self.status.setMinimumSize(QtCore.QSize(0, 50))
        self.status.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setBold(False)
        font.setWeight(50)
        self.status.setFont(font)
        self.status.setMouseTracking(True)
        self.status.setStyleSheet("background:rgba(0,0,0,0);\n"
"border-radius: 0px 0px 5px 5px;")
        self.status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status.setObjectName("status")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.status)
        self.horizontalLayout_2.setContentsMargins(12, 8, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.status_label = QtWidgets.QLabel(self.status)
        self.status_label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setMinimumSize(QtCore.QSize(0, 0))
        self.status_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.status_label.setFont(font)
        self.status_label.setMouseTracking(True)
        self.status_label.setStyleSheet("color: #8D98AA;\n"
"background:rgba(0,0,0,0);")
        self.status_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.status_label.setObjectName("status_label")
        self.horizontalLayout_2.addWidget(self.status_label)
        self.status_1 = QtWidgets.QFrame(self.status)
        self.status_1.setEnabled(True)
        self.status_1.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setBold(False)
        font.setWeight(50)
        self.status_1.setFont(font)
        self.status_1.setMouseTracking(True)
        self.status_1.setStyleSheet("background:rgba(0,0,0,0);\n"
"border-radius: 0px 0px 5px 5px;")
        self.status_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_1.setObjectName("status_1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.status_1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.retry_button = QtWidgets.QToolButton(self.status_1)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(10)
        self.retry_button.setFont(font)
        self.retry_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.retry_button.setStyleSheet("color: #0077ff;\n"
"background:rgba(0,0,0,0);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/image/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.retry_button.setIcon(icon2)
        self.retry_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.retry_button.setObjectName("retry_button")
        self.horizontalLayout_7.addWidget(self.retry_button)
        self.retry_label = QtWidgets.QLabel(self.status_1)
        self.retry_label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.retry_label.sizePolicy().hasHeightForWidth())
        self.retry_label.setSizePolicy(sizePolicy)
        self.retry_label.setMinimumSize(QtCore.QSize(550, 0))
        self.retry_label.setMaximumSize(QtCore.QSize(550, 16777215))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.retry_label.setFont(font)
        self.retry_label.setMouseTracking(True)
        self.retry_label.setStyleSheet("color: #4E5865;\n"
"background:rgba(0,0,0,0);")
        self.retry_label.setText("")
        self.retry_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.retry_label.setObjectName("retry_label")
        self.horizontalLayout_7.addWidget(self.retry_label)
        self.horizontalLayout_2.addWidget(self.status_1)
        self.verticalLayout_2.addWidget(self.status)
        self.status_2 = QtWidgets.QFrame(self.frame)
        self.status_2.setEnabled(True)
        self.status_2.setMinimumSize(QtCore.QSize(0, 50))
        self.status_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setBold(False)
        font.setWeight(50)
        self.status_2.setFont(font)
        self.status_2.setMouseTracking(True)
        self.status_2.setStyleSheet("background:rgba(0,0,0,0);\n"
"border-radius: 0px 0px 5px 5px;")
        self.status_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_2.setObjectName("status_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.status_2)
        self.horizontalLayout_4.setContentsMargins(12, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.exit_button = QtWidgets.QPushButton(self.status_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_button.sizePolicy().hasHeightForWidth())
        self.exit_button.setSizePolicy(sizePolicy)
        self.exit_button.setMinimumSize(QtCore.QSize(70, 29))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(10)
        self.exit_button.setFont(font)
        self.exit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_button.setStyleSheet("QPushButton {\n"
"color: #4E5865;\n"
"border: 1px solid #C3CEDF;\n"
"border-radius: 2px;\n"
"}\n"
"QPushButton:hover {\n"
"color: #52A3FF;\n"
"border: 1px solid #52A3FF;\n"
"border-radius: 2px;\n"
"}")
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout_4.addWidget(self.exit_button, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.status_2)
        self.title_2 = QtWidgets.QFrame(self.frame)
        self.title_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_2.sizePolicy().hasHeightForWidth())
        self.title_2.setSizePolicy(sizePolicy)
        self.title_2.setMinimumSize(QtCore.QSize(0, 300))
        self.title_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setBold(False)
        font.setWeight(50)
        self.title_2.setFont(font)
        self.title_2.setMouseTracking(True)
        self.title_2.setStyleSheet("background:rgba(0,0,0,0)")
        self.title_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_2.setObjectName("title_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.title_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2.addWidget(self.title_2)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.warning_label_1.setText(_translate("Form", "检测到您的设备当前没有安装conda环境，请根据"))
        self.warning_label_3.setText(_translate("Form", "进行安装"))
        self.title_label.setText(_translate("Form", "模型适配工具"))
        self.status_label.setText(_translate("Form", "正在检查环境..."))
        self.retry_button.setText(_translate("Form", "重新检测"))
        self.exit_button.setText(_translate("Form", "终止程序"))
