# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keypoint.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtGui
from PyQt5.QtCore import Qt
from src.labelme.labelme.convert_model.custom_widget.ui_element import EarlyStpPanel
class Ui_frame_body(object):
    def setupUi(self, frame_body):
        frame_body.setObjectName("frame_body")
        # frame_body.resize(720, 360)
        frame_body.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(frame_body)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_bg = QtWidgets.QFrame(frame_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_bg.sizePolicy().hasHeightForWidth())
        self.frame_bg.setSizePolicy(sizePolicy)
        # self.frame_bg.setMinimumSize(QtCore.QSize(720, 360))
        # 增加了两行显示早停参数界面，一行20像素，一行32像素
        self.frame_bg.setMaximumSize(QtCore.QSize(720, 360 + 20 + 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_bg.setFont(font)
        self.frame_bg.setStyleSheet("* {\n"
"border-radius: 5px 5px;\n"
"}\n"
"#frame_bg {\n"
"background: #FEFEFE;\n"
"margin: 5px;\n"
"border:1px solid #DFE5EF;\n"
"}")
        self.frame_bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bg.setObjectName("frame_bg")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_bg)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_header = QtWidgets.QFrame(self.frame_bg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_header.sizePolicy().hasHeightForWidth())
        self.frame_header.setSizePolicy(sizePolicy)
        self.frame_header.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_header.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_header.setFont(font)
        self.frame_header.setStyleSheet("#frame_header {\n"
"border-top:1px solid #DFE5EF;\n"
"border-bottom:1px solid #DFE5EF;\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"} ")
        self.frame_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header.setObjectName("frame_header")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_header)
        self.horizontalLayout_7.setContentsMargins(18, 0, 9, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_title = QtWidgets.QLabel(self.frame_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setText("Keypoint")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_7.addWidget(self.label_title)
        self.hide_button = QtWidgets.QPushButton(self.frame_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hide_button.sizePolicy().hasHeightForWidth())
        self.hide_button.setSizePolicy(sizePolicy)
        self.hide_button.setMinimumSize(QtCore.QSize(36, 0))
        self.hide_button.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hide_button.setFont(font)
        self.hide_button.setStyleSheet("QPushButton{\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #dddddd;\n"
"};")
        self.hide_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/image/new_minimize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hide_button.setIcon(icon)
        self.hide_button.setObjectName("hide_button")
        self.horizontalLayout_7.addWidget(self.hide_button)
        self.close_button = QtWidgets.QPushButton(self.frame_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_button.sizePolicy().hasHeightForWidth())
        self.close_button.setSizePolicy(sizePolicy)
        self.close_button.setMinimumSize(QtCore.QSize(36, 0))
        self.close_button.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.close_button.setFont(font)
        self.close_button.setStyleSheet("QPushButton{\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #dddddd;\n"
"};")
        self.close_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/image/new_close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon1)
        self.close_button.setIconSize(QtCore.QSize(16, 16))
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_7.addWidget(self.close_button)
        self.verticalLayout_2.addWidget(self.frame_header)
        self.frame = QtWidgets.QFrame(self.frame_bg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(9, 0, 9, 9)
        self.verticalLayout_4.setSpacing(9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.transform = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transform.sizePolicy().hasHeightForWidth())
        self.transform.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.transform.setFont(font)
        self.transform.setStyleSheet("color: #4E5865;")
        self.transform.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transform.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transform.setObjectName("transform")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.transform)
        self.horizontalLayout_2.setContentsMargins(9, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ds_label = QtWidgets.QLabel(self.transform)
        self.ds_label.setMinimumSize(QtCore.QSize(80, 0))
        self.ds_label.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        self.ds_label.setFont(font)
        self.ds_label.setText("Dataset Path")
        self.ds_label.setObjectName("ds_label")
        self.horizontalLayout_2.addWidget(self.ds_label)
        self.dataset = QtWidgets.QFrame(self.transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataset.sizePolicy().hasHeightForWidth())
        self.dataset.setSizePolicy(sizePolicy)
        self.dataset.setMinimumSize(QtCore.QSize(0, 34))
        self.dataset.setMaximumSize(QtCore.QSize(16777215, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataset.setFont(font)
        self.dataset.setStyleSheet("#dataset {\n"
"border:1px solid #C3CEDF;\n"
"border-radius: 2px;\n"
"} ")
        self.dataset.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dataset.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dataset.setObjectName("dataset")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dataset)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ds_line = QtWidgets.QLineEdit(self.dataset)
        self.ds_line.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ds_line.sizePolicy().hasHeightForWidth())
        self.ds_line.setSizePolicy(sizePolicy)
        self.ds_line.setMinimumSize(QtCore.QSize(0, 30))
        self.ds_line.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        self.ds_line.setFont(font)
        self.ds_line.setToolTip("")
        self.ds_line.setStatusTip("")
        self.ds_line.setStyleSheet("border: none;\n"
"background: #FEFEFE;\n"
"padding: 0px 5px;\n"
"color: #8D98AA;")
        self.ds_line.setText("")
        self.ds_line.setReadOnly(True)
        self.ds_line.setPlaceholderText("Press to select dataset path.")
        self.ds_line.setObjectName("ds_line")
        self.horizontalLayout.addWidget(self.ds_line)
        self.ds_button = QtWidgets.QPushButton(self.dataset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ds_button.sizePolicy().hasHeightForWidth())
        self.ds_button.setSizePolicy(sizePolicy)
        self.ds_button.setMinimumSize(QtCore.QSize(30, 30))
        self.ds_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(10)
        self.ds_button.setFont(font)
        self.ds_button.setToolTip("Press to select dataset path.")
        self.ds_button.setStyleSheet("QPushButton{\n"
"    background: #FEFEFE;\n"
"    color: #ffffff;\n"
"    border-radius: 2px 2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background: #FEFEFE;\n"
"}\n"
"QPushButton:pressed{\n"
"    background: #FEFEFE;\n"
"}")
        self.ds_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/image/new_more.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ds_button.setIcon(icon2)
        self.ds_button.setObjectName("ds_button")
        self.horizontalLayout.addWidget(self.ds_button)
        self.horizontalLayout_2.addWidget(self.dataset)
        self.verticalLayout_4.addWidget(self.transform)
        self.train = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.train.sizePolicy().hasHeightForWidth())
        self.train.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.train.setFont(font)
        self.train.setStyleSheet("color: #4E5865;")
        self.train.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.train.setFrameShadow(QtWidgets.QFrame.Raised)
        self.train.setObjectName("train")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.train)
        self.horizontalLayout_8.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.split_frame = QtWidgets.QFrame(self.train)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.split_frame.sizePolicy().hasHeightForWidth())
        self.split_frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.split_frame.setFont(font)
        self.split_frame.setStyleSheet("")
        self.split_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.split_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.split_frame.setObjectName("split_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.split_frame)
        self.horizontalLayout_9.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.split_label = QtWidgets.QLabel(self.split_frame)
        self.split_label.setMinimumSize(QtCore.QSize(80, 0))
        self.split_label.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        self.split_label.setFont(font)
        self.split_label.setText("Dataset Split")
        self.split_label.setObjectName("split_label")
        self.horizontalLayout_9.addWidget(self.split_label)
        self.split = QtWidgets.QFrame(self.split_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.split.sizePolicy().hasHeightForWidth())
        self.split.setSizePolicy(sizePolicy)
        self.split.setMinimumSize(QtCore.QSize(0, 34))
        self.split.setMaximumSize(QtCore.QSize(16777215, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.split.setFont(font)
        self.split.setStyleSheet("#split {\n"
"border:1px solid #C3CEDF;\n"
"border-radius: 2px;\n"
"} ")
        self.split.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.split.setFrameShadow(QtWidgets.QFrame.Raised)
        self.split.setObjectName("split")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.split)
        self.horizontalLayout_10.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.split_line = QtWidgets.QLineEdit(self.split)
        self.split_line.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.split_line.sizePolicy().hasHeightForWidth())
        self.split_line.setSizePolicy(sizePolicy)
        self.split_line.setMinimumSize(QtCore.QSize(0, 30))
        self.split_line.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        self.split_line.setFont(font)
        self.split_line.setStatusTip("")
        self.split_line.setStyleSheet("border: none;\n"
"background: #FEFEFE;\n"
"padding: 0px 5px;\n"
"color: #8D98AA;")
        self.split_line.setText("")
        self.split_line.setReadOnly(False)
        self.split_line.setPlaceholderText("Enter split ratio")
        self.split_line.setObjectName("split_line")
        self.horizontalLayout_10.addWidget(self.split_line)
        self.horizontalLayout_9.addWidget(self.split)
        self.horizontalLayout_8.addWidget(self.split_frame)
        self.train_frame = QtWidgets.QFrame(self.train)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.train_frame.sizePolicy().hasHeightForWidth())
        self.train_frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.train_frame.setFont(font)
        self.train_frame.setStyleSheet("")
        self.train_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.train_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.train_frame.setObjectName("train_frame")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.train_frame)
        self.horizontalLayout_16.setContentsMargins(25, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(18)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.epoch = QtWidgets.QLabel(self.train_frame)
        self.epoch.setMinimumSize(QtCore.QSize(60, 0))
        self.epoch.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        self.epoch.setFont(font)
        self.epoch.setText("Epoch")
        self.epoch.setObjectName("epoch")
        self.horizontalLayout_16.addWidget(self.epoch)
        self.epoch_frame = QtWidgets.QFrame(self.train_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.epoch_frame.sizePolicy().hasHeightForWidth())
        self.epoch_frame.setSizePolicy(sizePolicy)
        self.epoch_frame.setMinimumSize(QtCore.QSize(0, 34))
        self.epoch_frame.setMaximumSize(QtCore.QSize(16777215, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.epoch_frame.setFont(font)
        self.epoch_frame.setStyleSheet("#epoch_frame {\n"
"border:1px solid #C3CEDF;\n"
"border-radius: 2px;\n"
"} ")
        self.epoch_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.epoch_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.epoch_frame.setObjectName("epoch_frame")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.epoch_frame)
        self.horizontalLayout_23.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.epoch_line = QtWidgets.QLineEdit(self.epoch_frame)
        self.epoch_line.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.epoch_line.sizePolicy().hasHeightForWidth())
        self.epoch_line.setSizePolicy(sizePolicy)
        self.epoch_line.setMinimumSize(QtCore.QSize(0, 30))
        self.epoch_line.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        self.epoch_line.setFont(font)
        self.epoch_line.setStatusTip("")
        self.epoch_line.setStyleSheet("border: none;\n"
"background: #FEFEFE;\n"
"padding: 0px 5px;\n"
"color: #8D98AA;")
        self.epoch_line.setText("")
        self.epoch_line.setReadOnly(False)
        self.epoch_line.setPlaceholderText("Epoch")
        self.epoch_line.setObjectName("epoch_line")
        self.horizontalLayout_23.addWidget(self.epoch_line)
        self.horizontalLayout_16.addWidget(self.epoch_frame)
        self.batch = QtWidgets.QLabel(self.train_frame)
        self.batch.setMinimumSize(QtCore.QSize(60, 0))
        self.batch.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        self.batch.setFont(font)
        self.batch.setText("Batch")
        self.batch.setObjectName("batch")
        self.horizontalLayout_16.addWidget(self.batch)
        self.batch_frame = QtWidgets.QFrame(self.train_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batch_frame.sizePolicy().hasHeightForWidth())
        self.batch_frame.setSizePolicy(sizePolicy)
        self.batch_frame.setMinimumSize(QtCore.QSize(0, 34))
        self.batch_frame.setMaximumSize(QtCore.QSize(16777215, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.batch_frame.setFont(font)
        self.batch_frame.setStyleSheet("#batch_frame {\n"
"border:1px solid #C3CEDF;\n"
"border-radius: 2px;\n"
"} ")
        self.batch_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.batch_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.batch_frame.setObjectName("batch_frame")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.batch_frame)
        self.horizontalLayout_17.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.batch_line = QtWidgets.QLineEdit(self.batch_frame)
        self.batch_line.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batch_line.sizePolicy().hasHeightForWidth())
        self.batch_line.setSizePolicy(sizePolicy)
        self.batch_line.setMinimumSize(QtCore.QSize(0, 30))
        self.batch_line.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        self.batch_line.setFont(font)
        self.batch_line.setStatusTip("")
        self.batch_line.setStyleSheet("border: none;\n"
"background: #FEFEFE;\n"
"padding: 0px 5px;\n"
"color: #8D98AA;")
        self.batch_line.setText("")
        self.batch_line.setReadOnly(False)
        self.batch_line.setPlaceholderText("Batch")
        self.batch_line.setObjectName("batch_line")
        self.horizontalLayout_17.addWidget(self.batch_line)
        self.horizontalLayout_16.addWidget(self.batch_frame)
        self.horizontalLayout_8.addWidget(self.train_frame)
        self.verticalLayout_4.addWidget(self.train)
        self.pkg = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pkg.sizePolicy().hasHeightForWidth())
        self.pkg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pkg.setFont(font)
        self.pkg.setStyleSheet("color: #4E5865;")
        self.pkg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pkg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pkg.setObjectName("pkg")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.pkg)
        self.horizontalLayout_4.setContentsMargins(9, 0, -1, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pkg_label = QtWidgets.QLabel(self.pkg)
        self.pkg_label.setMinimumSize(QtCore.QSize(80, 0))
        self.pkg_label.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        self.pkg_label.setFont(font)
        self.pkg_label.setText("Output Path")
        self.pkg_label.setObjectName("pkg_label")
        self.horizontalLayout_4.addWidget(self.pkg_label)
        self.output_frame = QtWidgets.QFrame(self.pkg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_frame.sizePolicy().hasHeightForWidth())
        self.output_frame.setSizePolicy(sizePolicy)
        self.output_frame.setMinimumSize(QtCore.QSize(0, 34))
        self.output_frame.setMaximumSize(QtCore.QSize(16777215, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_frame.setFont(font)
        self.output_frame.setStyleSheet("#output_frame {\n"
"border:1px solid #C3CEDF;\n"
"border-radius: 2px;\n"
"} ")
        self.output_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_frame.setObjectName("output_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.output_frame)
        self.horizontalLayout_5.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.output_line = QtWidgets.QLineEdit(self.output_frame)
        self.output_line.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_line.sizePolicy().hasHeightForWidth())
        self.output_line.setSizePolicy(sizePolicy)
        self.output_line.setMinimumSize(QtCore.QSize(0, 30))
        self.output_line.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        self.output_line.setFont(font)
        self.output_line.setStatusTip("")
        self.output_line.setStyleSheet("border: none;\n"
"background: #FEFEFE;\n"
"padding: 0px 5px;\n"
"color: #8D98AA;")
        self.output_line.setReadOnly(False)
        self.output_line.setPlaceholderText("Press to select package output path.")
        self.output_line.setObjectName("output_line")
        self.horizontalLayout_5.addWidget(self.output_line)
        self.output_button = QtWidgets.QPushButton(self.output_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_button.sizePolicy().hasHeightForWidth())
        self.output_button.setSizePolicy(sizePolicy)
        self.output_button.setMinimumSize(QtCore.QSize(30, 30))
        self.output_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(10)
        self.output_button.setFont(font)
        self.output_button.setToolTip("Press to select package output path.")
        self.output_button.setStyleSheet("QPushButton{\n"
"    background: #FEFEFE;\n"
"    color: #ffffff;\n"
"    border-radius: 2px 2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background: #FEFEFE;\n"
"}\n"
"QPushButton:pressed{\n"
"    background: #FEFEFE;\n"
"}")
        self.output_button.setText("")
        self.output_button.setIcon(icon2)
        self.output_button.setObjectName("output_button")
        self.horizontalLayout_5.addWidget(self.output_button)
        self.horizontalLayout_4.addWidget(self.output_frame)
        self.verticalLayout_4.addWidget(self.pkg)
        self.progress = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress.sizePolicy().hasHeightForWidth())
        self.progress.setSizePolicy(sizePolicy)
        self.progress.setMinimumSize(QtCore.QSize(0, 0))
        self.progress.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progress.setFont(font)
        self.progress.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress.setObjectName("progress")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.progress)
        self.verticalLayout_3.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.progress_2 = QtWidgets.QFrame(self.progress)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_2.sizePolicy().hasHeightForWidth())
        self.progress_2.setSizePolicy(sizePolicy)
        self.progress_2.setMinimumSize(QtCore.QSize(0, 35))
        self.progress_2.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progress_2.setFont(font)
        self.progress_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_2.setObjectName("progress_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.progress_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.progress_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background: #DFE5EF;\n"
"    border-radius: 2px;\n"
"}\n"
"QProgressBar::chunk { \n"
"    background: #0077FF;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.progress_label = QtWidgets.QLabel(self.progress_2)
        self.progress_label.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        self.progress_label.setFont(font)
        self.progress_label.setStyleSheet("color: #000000;")
        self.progress_label.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_label.setObjectName("progress_label")
        self.horizontalLayout_3.addWidget(self.progress_label)
        self.verticalLayout_3.addWidget(self.progress_2)
        self.msg_label = QtWidgets.QLabel(self.progress)
        self.msg_label.setMinimumSize(QtCore.QSize(0, 0))
        self.msg_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        self.msg_label.setFont(font)
        self.msg_label.setStyleSheet("color:#000000;")
        self.msg_label.setText("")
        self.msg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.msg_label.setObjectName("msg_label")
        self.verticalLayout_3.addWidget(self.msg_label)

        #加载早停UI
        self.earlystp_panel = EarlyStpPanel("mIOU")
        self.verticalLayout_4.addSpacing(10)
        self.verticalLayout_4.addWidget(self.earlystp_panel)

        self.verticalLayout_4.addWidget(self.progress)
        self.start = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        self.start.setMinimumSize(QtCore.QSize(0, 31))
        self.start.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start.setFont(font)
        self.start.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.start.setFrameShadow(QtWidgets.QFrame.Raised)
        self.start.setObjectName("start")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.start)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.start_button = QtWidgets.QPushButton(self.start)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setMinimumSize(QtCore.QSize(90, 31))
        self.start_button.setMaximumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(10)
        self.start_button.setFont(font)
        self.start_button.setToolTip("Package")
        self.start_button.setStyleSheet("QPushButton{\n"
"    background: #0077FF;\n"
"    color: #ffffff;\n"
"    border-radius: 3px 3px;\n"
"}\n"
"QPushButton:hover{\n"
"    background: #52A3FF;\n"
"}\n"
"QPushButton:pressed{\n"
"    background: #0077FF;\n"
"}")
        self.start_button.setText("Package")
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_6.addWidget(self.start_button, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_4.addWidget(self.start)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_bg)

        self.retranslateUi(frame_body)
        QtCore.QMetaObject.connectSlotsByName(frame_body)

    def retranslateUi(self, frame_body):
        _translate = QtCore.QCoreApplication.translate
        frame_body.setWindowTitle(_translate("frame_body", "Form"))
        self.progress_label.setText(_translate("frame_body", "0%"))
